server:
  port: 8020
#当前服务在注册中心的名字
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #是否将当前服务的ip注册到EurekaServer
  instance:
    prefer-ip-address: true

