server:
  port: 8888
#当前服务在注册中心的名字
spring:
  application:
    name: configserver
#本地配置文件存放路径
  cloud:
    config:
      server:
        git:
          uri: https://github.com/497424232/demoSpringCloud
          search-paths: config
          username: iamchangmk@163.com
          password: cmk@github0806
        default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


