server:
  port: 8090
#当前服务在注册中心的名字
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      client:
        #设置开启请求跟踪
        enabled: true
    sampler:
      #设置采样比例，默认是1.0
      probability: 1.0
  zipkin:
    base-url:
      #zipkin server 地址
      defaultZone: http://localhost:9090/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
