server:
  port: 8010
#当前服务在注册中心的名字
spring:
  application:
    name: productor

#eureka服务端地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/
#      defaultZone: http://eureka8761.com:8761/euruka/,http://eureka8762.com:8762/euruka/,http://eureka8763.com:8763/euruka/
  instance:
    #是否将当前服务的ip注册到EurekaServer， 访问路径可以显示ip地址
    prefer-ip-address: true
    #处理别名
    instance-id: springcloud-productor

#配置点击配置机器跳转信息
info:
  company-name: cmk
  age: 28
  build.version: ${project.version}

