server:
  port: 8020
#当前服务在注册中心的名字
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/euruka/
      defaultZone: http://eureka8761.com:8761/euruka/,http://eureka8762.com:8762/euruka/,http://eureka8763.com:8763/euruka/
    register-with-eureka: false

  #是否将当前服务的ip注册到EurekaServer
#  instance:
#    prefer-ip-address: true

